---
title: '20190308'
author: "Kim"
date: "2019년 3월 8일"
output: html_document
---

```{r library,echo=FALSE, message=FALSE, results='hide', warning=FALSE}
library(dplyr)
library(tibble)   
library(ggiraphExtra)
library(maps)
library(ggplot2)
library(stringi)
library(ggiraph)
library(stringi)
library(kormaps2014)
library(plotly)
library(dygraphs)
library(xts)
library(gridExtra)
library(sqldf)
library(tm)
library(RColorBrewer)
library(wordcloud)
library(devtools)
library(twitteR)
library(RCurl) 
library(RJSONIO); library(stringr)
library(streamR); library(ROAuth)
library(rJava)
library(KoNLP)
library(rvest); library(httr); library(stringr); library(dplyr)
library(arulesViz) 
library(visNetwork)
library(arules); library(igraph); library(combinat)
library(arulesViz)
library(visNetwork)
library(psych)
```

### 1. 죽반과 매반의 수학성적은 차이가 없다?
```{r pf1, echo=TRUE, message=FALSE, results='hide', warning=FALSE}

load("data/data.rda")
data$avg = apply(data[,4:8], MARGIN = 1, FUN = mean)
s = data %>% filter(반 == '매') %>% select(avg)
mnkor = data %>% filter(반 %in% c('죽', '매')) %>% select(반,math)

mnkor$cls = factor(mnkor$반, levels=c('죽','매'), labels=c('죽', '매'))


describeBy(mnkor$math, mnkor$cls, mat = T)

layout(matrix(c(1,1,2,3), 2, 2, byrow = T)) 
boxplot(mnkor$math ~ mnkor$cls)
hist(mnkor$math[mnkor$cls == '죽'])
hist(mnkor$math[mnkor$cls == '매'])


var.test(mnkor$math ~ mnkor$cls, data =mnkor)
t.test(mnkor$math ~ mnkor$cls, data = mnkor, 
       alternative = c("two.sided"),
       var.equa = T,
       conf.level = 0.95)

mu = 63.4667; se = 2.144661; rn = sort(rnorm(1000, mu, se))

plot(rn, dnorm(rn, mu, se), col = 'green', type = 'l', main = '평균점수', xlim = c(50, 80), ylim = c(0, 0.25))

abline(v=mu, col='green', lty=5)
par(new = T)     

mu = 64.84167; se = 2.114145; rn = sort(rnorm(1000, mu, se))
plot(rn, dnorm(rn, mu, se), col = 'red', type = 'l', main = '평균점수', xlim = c(50, 80), ylim = c(0, 0.25))
abline(v=mu, col='red', lty=5)
legend('topright',
         legend=c('죽', '매'),
         pch=8,
         col=c('green', 'red'),
         bg='gray')
```

###2. 4개반 수학성적의 유사도(동질의 정도)를 분석하시오
```{r pf2, echo=TRUE, message=FALSE, results='hide', warning=FALSE}
math_data = data %>% select (반, math)
describeBy(math_data$math, math_data$반, mat = T)
boxplot(math_data$math ~ math_data$반)

bartlett.test(math_data$math ~ math_data$반, data = math_data) 

aaa = aov(math_data$math ~ math_data$반, data=math_data)
summary(aaa)
TukeyHSD(aaa)
plot(TukeyHSD(aaa))


draw = function(rn, mu, se, col) {
  plot(rn, dnorm(rn, mu, se), col=col, type = 'l',
       xlim = c(50, 80), ylim = c(0, 0.25))
  abline(v=mu, col=col, lty=5)
}

mu = 63.59167; se = 2.020535; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'red')
par(new = T)
mu = 63.08333; se = 2.028632; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'blue')
par(new = T)
mu = 63.84167; se = 2.114145; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'green')
par(new = T)
mu = 63.4667; se = 2.144661; rn = sort(rnorm(1000, mu, se))
draw(rn, mu, se, 'black')
legend('topright',
         legend=c('국', '난', '매', '죽'),
         pch=8,
         col=c('red', 'blue', 'green', 'black'),
         bg='gray')

```

### 3.전교생의 국어성적과 영어석적에 대한 상관분석(Correlation)을 수행 하시오. 
```{r,  echo=TRUE, message=FALSE, results='hide', warning=FALSE}
pf3 = data %>% select(kor,eng)

describe(pf3)
pairs.panels(pf3)

cor(pf3, use = "complete.obs", method = c("pearson"))
plot(kor ~ eng, data=pf3)
abline(lm(kor ~ eng, data=pf3), col='red')     
```

### 4.mpg데이터의 displ, cyl, trans, cty, hwy 중 1999년과 2008년 두 해의 고객 만족도가 0과 1이라고 했을 때, 어떤 요소가 만족도에 많은 기여를 했는지 로지스틱 회귀분석하시오.
```{r, pf4, echo=TRUE, message=FALSE,  warning=FALSE }
unique(mpg$trans); unique(mpg$year);

pf4 =mpg %>% mutate(trs = ifelse(substr(trans, 1, 4) == 'auto', 1, 0), 
            y = ifelse(year == 1999, 0, 1)) %>%
  select(y, displ, cyl, trs, cty, hwy)

describe(pf4)
pairs.panels(pf4)

glmdata = glm(y ~ displ+cyl+cty+hwy, family = binomial, data=pf4)
summary(glmdata)  # Estimate: 기울기(비례/반비례), Pr: 0.05보다 작으면 영향이 있다
```
GLM의 결과는 displ과 hwy의 기여가 더 높았다는 것을 보여준다.
